[project]
name = "nf-core-stats"
version = "0.1.0"
description = "DLT pipeline for nf-core stats collection"
authors = [
    { name = "nf-core team" }
]
dependencies = [
    "dlt[duckdb]>=0.3.6",
    "python-dotenv==1.0.0",
    "requests>=2.31.0",
]
requires-python = ">=3.9"
